#!/usr/bin/env python3
"""
Test Three Services Integration
Data Ingestor → Strategies → Risk Manager
"""

import asyncio
import logging
import sys
from pathlib import Path

# Add lib to path
sys.path.insert(0, str(Path(__file__).parent))

from lib.settings import get_settings
from lib.bus import connect_bus, get_bus

# Import services
sys.path.insert(0, str(Path(__file__).parent / "apps" / "data_ingestor"))
sys.path.insert(0, str(Path(__file__).parent / "apps" / "strategies"))
sys.path.insert(0, str(Path(__file__).parent / "apps" / "risk_manager"))

from apps.data_ingestor.main import AlpacaDataIngestor
from apps.strategies.main import StrategyEngine
from apps.risk_manager.main import RiskManager

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

async def test_complete_pipeline():
    """Test the complete trading pipeline"""
    logger.info("🚀 Testing Complete Trading Pipeline")
    logger.info("Data Ingestor → Strategies → Risk Manager")
    logger.info("=" * 60)
    
    # Connect to shared message bus
    if not connect_bus():
        logger.error("Failed to connect to message bus")
        return False
    
    bus = get_bus()
    
    # Initialize services
    ingestor = AlpacaDataIngestor()
    strategies = StrategyEngine()
    risk_manager = RiskManager()
    
    # Track results
    signals_generated = []
    order_intents_created = []
    
    async def signal_monitor():
        """Monitor signals generated by strategies"""
        async for signal in bus.subscribe_signals():
            signals_generated.append(signal)
            logger.info(f"📊 Signal: {signal.side} {signal.symbol} "
                       f"(confidence: {signal.confidence:.1%}) from {signal.source}")
    
    async def order_intent_monitor():
        """Monitor order intents created by risk manager"""
        async for order_intent in bus.subscribe_order_intents():
            order_intents_created.append(order_intent)
            logger.info(f"💼 Order Intent: {order_intent.side} {order_intent.quantity:.0f} "
                       f"{order_intent.symbol} @ ${order_intent.price:.2f}")
    
    try:
        # Start monitoring tasks
        signal_task = asyncio.create_task(signal_monitor())
        order_task = asyncio.create_task(order_intent_monitor())
        
        # Start services
        logger.info("📊 Starting strategy engine...")
        strategies.running = True
        strategy_consume_task = asyncio.create_task(strategies.consume_bars())
        
        logger.info("💼 Starting risk manager...")
        risk_manager.running = True
        risk_consume_task = asyncio.create_task(risk_manager.consume_signals())
        
        # Give services time to subscribe
        await asyncio.sleep(2)
        
        # Ingest data to trigger the pipeline
        logger.info("📈 Starting data ingestion (3 days)...")
        await ingestor.ingest_historical_data(days_back=3)
        
        # Wait for processing
        logger.info("⏳ Waiting for signal generation and processing...")
        
        # Wait up to 45 seconds for order intents to be created
        try:
            await asyncio.wait_for(
                asyncio.sleep(0.1) if len(order_intents_created) > 0 
                else asyncio.sleep(45), 
                timeout=45
            )
        except asyncio.TimeoutError:
            pass
        
        # Cancel tasks
        signal_task.cancel()
        order_task.cancel()
        strategy_consume_task.cancel()
        risk_consume_task.cancel()
        
        # Results
        logger.info("\n" + "=" * 60)
        logger.info("PIPELINE TEST RESULTS")
        logger.info("=" * 60)
        logger.info(f"📊 Signals Generated: {len(signals_generated)}")
        logger.info(f"💼 Order Intents Created: {len(order_intents_created)}")
        
        if signals_generated:
            logger.info("\n📊 Signals Generated:")
            for i, signal in enumerate(signals_generated):
                logger.info(f"  {i+1}. {signal.side} {signal.symbol} "
                           f"@ ${signal.price:.2f} ({signal.confidence:.1%}) - {signal.source}")
        
        if order_intents_created:
            logger.info("\n💼 Order Intents Created:")
            for i, order in enumerate(order_intents_created):
                logger.info(f"  {i+1}. {order.side} {order.quantity:.0f} {order.symbol} "
                           f"@ ${order.price:.2f} (ID: {order.client_order_id})")
        
        # Success criteria
        pipeline_success = len(signals_generated) > 0 and len(order_intents_created) > 0
        
        if pipeline_success:
            logger.info("\n🎉 Complete pipeline test PASSED!")
            logger.info("✅ Data flows correctly through all three services")
        else:
            logger.info("\n⚠️  Pipeline test partially successful:")
            if len(signals_generated) == 0:
                logger.info("❌ No signals generated (strategies may be too conservative)")
            if len(order_intents_created) == 0:
                logger.info("❌ No order intents created (risk manager may be rejecting signals)")
        
        return pipeline_success
        
    except Exception as e:
        logger.error(f"❌ Pipeline test failed: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    finally:
        # Cleanup
        ingestor.running = False
        strategies.running = False
        risk_manager.running = False

async def main():
    """Run the complete pipeline test"""
    settings = get_settings()
    logger.info(f"Configuration: {settings.symbols_list}, Paper: {settings.is_paper_trading}")
    
    success = await test_complete_pipeline()
    
    if success:
        logger.info("\n🚀 Ready to implement executor and API services!")
    else:
        logger.info("\n🔧 Pipeline needs refinement before proceeding.")

if __name__ == "__main__":
    asyncio.run(main())