#!/usr/bin/env python3
"""
Complete System Test - All 4 Services
Data Ingestor → Strategies → Risk Manager → Executor
"""

import asyncio
import logging
import sys
from pathlib import Path

# Add lib to path
sys.path.insert(0, str(Path(__file__).parent))

from lib.settings import get_settings
from lib.bus import connect_bus, get_bus

# Import all services
sys.path.insert(0, str(Path(__file__).parent / "apps" / "data_ingestor"))
sys.path.insert(0, str(Path(__file__).parent / "apps" / "strategies"))
sys.path.insert(0, str(Path(__file__).parent / "apps" / "risk_manager"))
sys.path.insert(0, str(Path(__file__).parent / "apps" / "executor"))

from apps.data_ingestor.main import AlpacaDataIngestor
from apps.strategies.main import StrategyEngine
from apps.risk_manager.main import RiskManager
from apps.executor.main import AlpacaExecutor

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

async def test_complete_trading_system():
    """Test the complete end-to-end trading system"""
    logger.info("🚀 COMPLETE TRADING SYSTEM TEST")
    logger.info("Data Ingestor → Strategies → Risk Manager → Executor")
    logger.info("=" * 70)
    
    # Connect to shared message bus
    if not connect_bus():
        logger.error("Failed to connect to message bus")
        return False
    
    bus = get_bus()
    
    # Initialize all services
    ingestor = AlpacaDataIngestor()
    strategies = StrategyEngine()
    risk_manager = RiskManager()
    executor = AlpacaExecutor()
    
    # Track all events
    signals_generated = []
    order_intents_created = []
    order_fills_executed = []
    system_events = []
    
    async def signal_monitor():
        """Monitor signals generated by strategies"""
        async for signal in bus.subscribe_signals():
            signals_generated.append(signal)
            logger.info(f"📊 SIGNAL: {signal.side} {signal.symbol} "
                       f"(confidence: {signal.confidence:.1%}) from {signal.source}")
    
    async def order_intent_monitor():
        """Monitor order intents created by risk manager"""
        async for order_intent in bus.subscribe_order_intents():
            order_intents_created.append(order_intent)
            logger.info(f"💼 ORDER INTENT: {order_intent.side} {order_intent.quantity:.0f} "
                       f"{order_intent.symbol} @ ${order_intent.price:.2f}")
    
    async def order_fill_monitor():
        """Monitor order fills from executor"""
        async for order_fill in bus.subscribe_order_fills():
            order_fills_executed.append(order_fill)
            logger.info(f"✅ ORDER FILLED: {order_fill.side} {order_fill.fill_quantity:.0f} "
                       f"{order_fill.symbol} @ ${order_fill.fill_price:.2f} "
                       f"(Total: ${order_fill.total_value:,.2f})")
    
    async def system_event_monitor():
        """Monitor system events"""
        async for event in bus.subscribe_system_events():
            system_events.append(event)
            if event.event_type in ["order_executed", "order_error", "signal_approved", "signal_rejected"]:
                logger.info(f"🔔 EVENT: {event.event_type} from {event.source}")
    
    try:
        # Start all monitoring tasks
        signal_task = asyncio.create_task(signal_monitor())
        order_intent_task = asyncio.create_task(order_intent_monitor())
        order_fill_task = asyncio.create_task(order_fill_monitor())
        system_task = asyncio.create_task(system_event_monitor())
        
        # Start all services
        logger.info("📊 Starting strategy engine...")
        strategies.running = True
        strategy_task = asyncio.create_task(strategies.consume_bars())
        
        logger.info("💼 Starting risk manager...")
        risk_manager.running = True
        risk_task = asyncio.create_task(risk_manager.consume_signals())
        
        logger.info("⚡ Starting executor...")
        # Verify executor account first
        if not await executor.verify_account_status():
            logger.error("Executor account verification failed")
            return False
        
        executor.running = True
        executor_task = asyncio.create_task(executor.consume_order_intents())
        
        # Give all services time to start and subscribe
        await asyncio.sleep(3)
        
        # Trigger the pipeline with historical data
        logger.info("📈 Starting data ingestion to trigger complete pipeline...")
        await ingestor.ingest_historical_data(days_back=3)
        
        # Wait for the complete pipeline to execute
        logger.info("⏳ Waiting for complete pipeline execution...")
        
        # Wait up to 60 seconds for order fills to be executed
        timeout_seconds = 60
        start_time = asyncio.get_event_loop().time()
        
        while (asyncio.get_event_loop().time() - start_time) < timeout_seconds:
            if len(order_fills_executed) > 0:
                logger.info("🎯 Order fill detected! Waiting a bit more for any additional orders...")
                await asyncio.sleep(10)  # Wait 10 more seconds for additional orders
                break
            await asyncio.sleep(1)
        
        # Cancel all tasks
        for task in [signal_task, order_intent_task, order_fill_task, system_task, 
                    strategy_task, risk_task, executor_task]:
            task.cancel()
        
        # Results summary
        logger.info("\n" + "=" * 70)
        logger.info("COMPLETE SYSTEM TEST RESULTS")
        logger.info("=" * 70)
        
        logger.info(f"📊 Signals Generated: {len(signals_generated)}")
        logger.info(f"💼 Order Intents Created: {len(order_intents_created)}")
        logger.info(f"✅ Orders Executed: {len(order_fills_executed)}")
        logger.info(f"🔔 System Events: {len(system_events)}")
        
        # Detailed results
        if signals_generated:
            logger.info("\n📊 SIGNALS GENERATED:")
            for i, signal in enumerate(signals_generated):
                logger.info(f"  {i+1}. {signal.side} {signal.symbol} @ ${signal.price:.2f} "
                           f"({signal.confidence:.1%}) - {signal.source}")
        
        if order_intents_created:
            logger.info("\n💼 ORDER INTENTS CREATED:")
            for i, order in enumerate(order_intents_created):
                logger.info(f"  {i+1}. {order.side} {order.quantity:.0f} {order.symbol} "
                           f"@ ${order.price:.2f} (ID: {order.client_order_id})")
        
        if order_fills_executed:
            logger.info("\n✅ ORDERS EXECUTED:")
            total_value = 0
            for i, fill in enumerate(order_fills_executed):
                logger.info(f"  {i+1}. {fill.side} {fill.fill_quantity:.0f} {fill.symbol} "
                           f"@ ${fill.fill_price:.2f} = ${fill.total_value:,.2f}")
                total_value += fill.total_value
            
            logger.info(f"\n💰 TOTAL TRADING VOLUME: ${total_value:,.2f}")
        
        # Success criteria
        complete_success = (len(signals_generated) > 0 and 
                          len(order_intents_created) > 0 and 
                          len(order_fills_executed) > 0)
        
        logger.info("\n" + "=" * 70)
        
        if complete_success:
            logger.info("🎉 COMPLETE SYSTEM TEST PASSED!")
            logger.info("✅ End-to-end trading pipeline working correctly")
            logger.info("✅ Real orders executed in Alpaca paper trading")
            logger.info("✅ All services communicating properly")
            logger.info("\n🚀 TRADING PLATFORM IS FULLY OPERATIONAL!")
        else:
            logger.info("⚠️  System test partially successful:")
            if len(signals_generated) == 0:
                logger.info("❌ No signals generated")
            elif len(order_intents_created) == 0:
                logger.info("❌ Signals generated but no order intents created")
            elif len(order_fills_executed) == 0:
                logger.info("❌ Order intents created but no orders executed")
        
        return complete_success
        
    except Exception as e:
        logger.error(f"❌ Complete system test failed: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    finally:
        # Cleanup all services
        ingestor.running = False
        strategies.running = False
        risk_manager.running = False
        executor.running = False

async def main():
    """Run the complete system test"""
    settings = get_settings()
    
    logger.info("🧪 ALGORITHMIC TRADING PLATFORM - COMPLETE SYSTEM TEST")
    logger.info("=" * 70)
    logger.info(f"Configuration:")
    logger.info(f"  Symbols: {settings.symbols_list}")
    logger.info(f"  Paper Trading: {settings.is_paper_trading}")
    logger.info(f"  Portfolio Value: $100,000")
    logger.info(f"  Max Position Size: {settings.max_position_size:.1%}")
    logger.info("")
    
    success = await test_complete_trading_system()
    
    logger.info("\n" + "=" * 70)
    if success:
        logger.info("🏆 TRADING PLATFORM VALIDATION COMPLETE!")
        logger.info("The system is ready for production deployment.")
    else:
        logger.info("🔧 System requires further refinement.")

if __name__ == "__main__":
    asyncio.run(main())